name: GCP Production CI/CD Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - cicd/pipeline
  workflow_dispatch:

env:
  PROJECT_ID: "training-batch-05"
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  DATABASE_URL_PRODUCTION: "${{ secrets.DATABASE_URL_PRODUCTION }}"
  SECRET_KEY: "${{ secrets.SECRET_KEY }}"
  CLOUDINARY_CLOUD_NAME: "${{ secrets.CLOUDINARY_CLOUD_NAME }}"
  CLOUDINARY_API_KEY: "${{ secrets.CLOUDINARY_API_KEY }}"
  CLOUDINARY_SECRET_KEY: "${{ secrets.CLOUDINARY_SECRET_KEY }}"
  ORIGIN_URL: "${{ secrets.ORIGIN_URL }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-dockast1-docker.pkg.dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/beetrack-back/prod:latest
          cache-from: type=registry,ref=us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/beetrack-back/buildcache
          cache-to: type=registry,ref=us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/beetrack-back/buildcache,mode=max

  # deploy-to-GCP:
  #   runs-on: [self-hosted]
  #   needs: build-and-push-image
  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  #     - name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v2
  #       with:
  #         project_id: ${{ env.PROJECT_ID }}

  #     - name: Configure Docker for Artifact Registry
  #       run: |
#         gcloud auth configure-dockast1-docker.pkg.dev --quiet
#     - name: Pull the latest image
#       run: |
#         docker puast1-docker.pkg.dev/${{ env.PROJECT_ID }}/beetrack-back/prod:latest
#     - name: Stop and remove existing container
#       run: |
#         docker stop beetrack-back || true
#         docker rm beetrack-back || true
#     - name: Deploy to Cloud Run
#       run: |
#         docker run -d
#           -p 8000:8000
#       PYTHONUNBUFFERED: 1
#       PORT: 8000
#       PYTHONPATH: /app:/app/beetrack:/usr/local/lib/python3.11/site-packages
#       DATABASE_URL: "${{ secrets.DATABASE_URL }}"
#       SECRET_KEY: "${{ secrets.SECRET_KEY }}"
#       DEBUG: false
#           --name beetrack-back
#           --restart: unless-stopped
#        ast1-docker.pkg.dev/${{ env.PROJECT_ID }}/beetrack-back/prod:latest
